# fly.toml app configuration file generated for team-petpar on 2024-01-24T17:40:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "team-petpar"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
